In [1]:
import pandas as pd
file_path=data/'Online retail.xlsx'
df=pd.read_excel(file_path)

NameError: name 'data' is not defined

In [2]:
file_path=data\'Online retail.xlsx'
df=pd.read_excel(file_path)

SyntaxError: unexpected character after line continuation character (2149503893.py, line 1)

In [3]:
file_path='data/Online retail.xlsx'
df=pd.read_excel(file_path)

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [1]:
file_path=data/'Online retail.xlsx'
df=pd.read_excel(file_path)

NameError: name 'data' is not defined

In [7]:
import pandas as pd
file_path='data/Online_retail.csv'
df=pd.read_csv(file_path)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [2]:
df.to_csv('data/Online_retail.csv', index=False)
print("successfully coverted Online Retail.xlsx to Online_retail.csv")

successfully coverted Online Retail.xlsx to Online_retail.csv

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [9]:
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])
print(df.dtypes)

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [10]:
df=df[df['Quantity']>0]
df.dropna(subset=['CustomerID'],inplace=True)
print(f"shape of cleaned dataframe : {df.shape}")

shape of cleaned dataframe : (397924, 8)

In [11]:
df['CustomerID']=df['CustomerID'].astype('str')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397924 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  object
 1   StockCode    397924 non-null  object
 2   Description  397924 non-null  object
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  datetime64[ns]
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  object
 7   Country      397924 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 27.3+ MB

In [13]:
basket=(df.groupby(['InvoiceNo','Description'])['Quantity'].sum().unstack().reset_index().fillna(0).set_index('InvoiceNo'))
basket.head()

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536366,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536369,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
basket.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18536 entries, 536365 to 581587
Columns: 3877 entries,  4 PURPLE FLOCK DINNER CANDLES to ZINC WIRE SWEETHEART LETTER TRAY
dtypes: float64(3877)
memory usage: 548.4+ MB

In [15]:
basket.iloc[:,-5:]

Description,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,
536365,0.0,0.0,0.0,0.0,0.0
536366,0.0,0.0,0.0,0.0,0.0
536367,0.0,0.0,0.0,0.0,0.0
536368,0.0,0.0,0.0,0.0,0.0
536369,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...
581583,0.0,0.0,0.0,0.0,0.0
581584,0.0,0.0,0.0,0.0,0.0
581585,0.0,0.0,24.0,0.0,0.0
581586,0.0,0.0,0.0,0.0,0.0
581587,0.0,0.0,0.0,0.0,0.0

In [19]:
def encodeunits(x):
    if x<=0:
        return 0
    if x>=1:
        return 1

basket_sets=basket.applymap(encodeunits)
basket_sets.iloc[:,-5:]

C:\Users\gokul\AppData\Local\Temp\ipykernel_22084\1456655442.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  basket_sets=basket.applymap(encodeunits)

Description,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,
536365,0,0,0,0,0
536366,0,0,0,0,0
536367,0,0,0,0,0
536368,0,0,0,0,0
536369,0,0,0,0,0
...,...,...,...,...,...
581583,0,0,0,0,0
581584,0,0,0,0,0
581585,0,0,1,0,0
581586,0,0,0,0,0
581587,0,0,0,0,0

In [20]:
basket_sets=(basket_sets>0).astype(int)
basket_sets.iloc[:,-5:]

Description,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,
536365,0,0,0,0,0
536366,0,0,0,0,0
536367,0,0,0,0,0
536368,0,0,0,0,0
536369,0,0,0,0,0
...,...,...,...,...,...
581583,0,0,0,0,0
581584,0,0,0,0,0
581585,0,0,1,0,0
581586,0,0,0,0,0
581587,0,0,0,0,0

In [21]:
basket_sets.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18536 entries, 536365 to 581587
Columns: 3877 entries,  4 PURPLE FLOCK DINNER CANDLES to ZINC WIRE SWEETHEART LETTER TRAY
dtypes: int64(3877)
memory usage: 548.4+ MB

In [27]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets=apriori(basket_sets,min_support=0.01,use_colnames=True,low_memory=True)
frequent_itemsets.sort_values(by='support',ascending=False).head(10)

c:\Users\gokul\OneDrive\Desktop\churn_analytics_platform\venv\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

      support                              itemsets
587  0.106334  (WHITE HANGING HEART T-LIGHT HOLDER)
414  0.091929            (REGENCY CAKESTAND 3 TIER)
247  0.086319             (JUMBO BAG RED RETROSPOT)
338  0.074450                       (PARTY BUNTING)
38   0.074180       (ASSORTED COLOUR BIRD ORNAMENT)
282  0.069486             (LUNCH BAG RED RETROSPOT)
468  0.061826   (SET OF 3 CAKE TINS PANTRY DESIGN )
374  0.059290                             (POSTAGE)
274  0.056754             (LUNCH BAG  BLACK SKULL.)
323  0.055514     (PACK OF 72 RETROSPOT CAKE CASES)

In [28]:
from mlxtend.frequent_patterns import association_rules

# Generate rules with a lift of at least 1
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

# Display the rules sorted by confidence and lift
rules.sort_values(by=['confidence', 'lift'], ascending=[False, False]).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
901,"(POPPY'S PLAYHOUSE LIVINGROOM , POPPY'S PLAYHO...",(POPPY'S PLAYHOUSE KITCHEN),0.011060,0.018666,0.010035,0.907317,48.607021,1.0,0.009828,10.588073,0.990380,0.509589,0.905554,0.722445
906,"(REGENCY CAKESTAND 3 TIER, ROSES REGENCY TEACU...",(GREEN REGENCY TEACUP AND SAUCER),0.014297,0.037279,0.012894,0.901887,24.193015,1.0,0.012361,9.812351,0.972570,0.333333,0.898088,0.623881
536,(REGENCY TEA PLATE PINK),(REGENCY TEA PLATE GREEN ),0.012085,0.014566,0.010898,0.901786,61.909259,1.0,0.010722,10.033507,0.995882,0.691781,0.900334,0.824967
618,"(ROSES REGENCY TEACUP AND SAUCER , PINK REGENC...",(GREEN REGENCY TEACUP AND SAUCER),0.023522,0.037279,0.021040,0.894495,23.994742,1.0,0.020163,9.124923,0.981409,0.529172,0.890410,0.729447
908,"(REGENCY CAKESTAND 3 TIER, GREEN REGENCY TEACU...",(ROSES REGENCY TEACUP AND SAUCER ),0.014620,0.042242,0.012894,0.881919,20.877710,1.0,0.012276,8.111012,0.966228,0.293252,0.876711,0.593578
541,(REGENCY TEA PLATE PINK),(REGENCY TEA PLATE ROSES ),0.012085,0.017695,0.010628,0.879464,49.700457,1.0,0.010414,8.149491,0.991866,0.554930,0.877293,0.740037
612,"(REGENCY CAKESTAND 3 TIER, PINK REGENCY TEACUP...",(GREEN REGENCY TEACUP AND SAUCER),0.016670,0.037279,0.014620,0.877023,23.526037,1.0,0.013999,7.828443,0.973726,0.371742,0.872261,0.634604
900,"(POPPY'S PLAYHOUSE LIVINGROOM , POPPY'S PLAYHO...",(POPPY'S PLAYHOUSE BEDROOM ),0.011599,0.017048,0.010035,0.865116,50.746188,1.0,0.009837,7.287403,0.991798,0.539130,0.862777,0.726862
895,"(REGENCY CAKESTAND 3 TIER, PINK REGENCY TEACUP...",(ROSES REGENCY TEACUP AND SAUCER ),0.016670,0.042242,0.014297,0.857605,20.302132,1.0,0.013592,6.726072,0.966862,0.320435,0.851325,0.598024
506,(POPPY'S PLAYHOUSE LIVINGROOM ),(POPPY'S PLAYHOUSE KITCHEN),0.013595,0.018666,0.011599,0.853175,45.706487,1.0,0.011345,6.683678,0.991602,0.561358,0.850382,0.737281